setup:
  seed: 314159
  outputDir: ./results
  enableTraining: true
  enableEvaluation: false
  enableExport: false

model:
  arch: resnet18
  numClasses: 2
  weights: DEFAULT
  unfreezeAllParams: false

dataset:
  trainsetDir: /dataset/train/
  valsetDir: /dataset/val/
  batchSize: 8
  numWorkers: 4

preprocessing:
  width: 48
  height: 48
  interpolation: INTER_CUBIC
  maintainAspectRatio: true
  padding: bottomRight
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  hflipProb: 0.5
  vflipProb: 0.5
  maxRotate: 10
  centorCrop: false
  randomCrop: false
  grayScale: false
  randomColorAugmentation: false

training:
  trainModel:
    numEpochs: 3
    standard: loss                          # available choice: loss, acc

  scheduler:
    name: step                              # ["step", "cosine"]
    lrMin: 0
    stepSize: 30                            # Only for step
    gamma: 0.1                              # Only for step

  optimizer:
    name: adam                              # ["sgd", "rmsprop", "adam", "adamw"]
    lr: 0.001
    weight_decay: 0
    momentum: 0.9                           # Only for sgd / rmsprop
    alpha: 0.99                             # Only for rmsprop
    betas: [0.9, 0.999]                     # Only for adam / adamw

evaluation:
  evalsetDir: /dataset/eval
  modelPath: /results/bestModel.pt

export:
  saveLastWeight: true
  saveBestWeight: true
  exportLastWeight: true
  exportBestWeight: true
